export const CHARS = [
  { id: "alejandro", emoji: "🪰", name: "ALEJANDRO R.", form: "Mosca boxeadora", ab: "FLY PUNCH", spd: 4.4, jump: 10.5, cd: 0.25,
    tip: "X: puñetazo · mantén salto para planear",
    voice: ["¿Puedo hacerle una foto a tu perro?"] },
  { id: "ale", emoji: "🫒", name: "ALE GRACIANO", form: "Botella de aceite", ab: "OIL SLIDE", spd: 4.0, jump: 9.5, cd: 1.0,
    tip: "X: derrámate y deslízate arrollando",
    voice: ["Toma aceituna."] },
  { id: "alvaroM", emoji: "🧮", name: "ÁLVARO MERINO", form: "Calculadora", ab: "ERROR 404", spd: 2.9, jump: 9, cd: 0.8,
    tip: "X: lanza una operación que explota",
    voice: ["Superior."] },
  { id: "alvaroP", emoji: "🎙️", name: "ÁLVARO", form: "Micro de podcast", ab: "PODCAST ATTACK", spd: 3.6, jump: 9.5, cd: 0.7,
    tip: "X: onda sonora de largo alcance",
    voice: ["¿Cuánto tiempo le has dedicado?"] },
  { id: "ana", emoji: "🦁", name: "ANA", form: "Escaladora leona", ab: "TREPAR", spd: 4.0, jump: 10, cd: 0.25,
    tip: "B: Trepar paredes (↑/↓)",
    voice: ["Esto no funciona."] },
  { id: "beltran", emoji: "🔵", name: "BELTRÁN", form: "Carrete azul", ab: "SLACK SPAM", spd: 3.4, jump: 9.5, cd: 0.28,
    tip: "X: lanza mensajes de Slack · Abajo/Mantén: Escudo",
    voice: ["Eso lo podemos vender ya."] },
  { id: "bruno", emoji: "🗿", name: "BRUNO", form: "Tótem multicara", ab: "MULTIFACE", spd: 3.0, jump: 9, cd: 2.5,
    tip: "X: una cara aleatoria hace algo distinto",
    voice: ["Chof chof."] },
  { id: "gonzalo", emoji: "🥦", name: "GONZALO", form: "Brócoli", ab: "BROCCOLI RAGE", spd: 3.2, jump: 9.5, cd: 1.2,
    tip: "X: te multiplicas en mini-brócolis",
    voice: [
      "¿Por qué los pájaros vuelan hacia el sur? Porque es demasiado lejos para ir andando.",
      "¿Qué le dice un semáforo a otro? No me mires, que me estoy cambiando.",
      "¿Cómo se llama el campeón de buceo de España? Ahogaíto.",
      "¿Qué hace una abeja en el gimnasio? ¡Zum-ba!",
      "¿Por qué el libro de matemáticas estaba triste? Porque tenía demasiados problemas.",
      "¿Qué le dice un jardinero a otro? Me pasa la vida arreglando entuertos.",
      "¿Cuál es el colmo de un electricista? Que su hijo sea una luz y su mujer una lámpara.",
      "¿Por qué los esqueletos no se pelean? Porque no tienen agallas."
    ] },
  { id: "javi", emoji: "☭", name: "JAVI", form: "Señal comunista", ab: "WORKERS UNITED", spd: 3.4, jump: 9, cd: 1.4,
    tip: "X: invoca trabajadores en marcha",
    voice: ["¡Arriba la clase trabajadora!"] },
  { id: "jesus", emoji: "🍺", name: "JESÚS", form: "Botella de Cruzcampo", ab: "CRUZCAMPO SMASH", spd: 2.6, jump: 9, cd: 0.6,
    tip: "X: smash de área (en el aire, se lanza al suelo)",
    voice: ["¿Nos echamos una Cruzcampo?"] },
  { id: "joseluis", emoji: "🖨️", name: "JOSÉ LUIS", form: "Impresora 3D", ab: "PRINT", spd: 3.0, jump: 9.5, cd: 0.4,
    tip: "X: imprime una plataforma (máx. 3)",
    voice: ["Hay dos partes.", "No se pueden meter links en los microfrontends."] },
  { id: "josu", emoji: "🥮", name: "JOSU", form: "Panetón escalador", ab: "PANETÓN CLIMB", spd: 4.0, jump: 10, cd: 0.6,
    tip: "Rebota en paredes con salto · X: bote diagonal",
    voice: ["No, eso no es vegano."] },
  { id: "juan", emoji: "📻", name: "JUAN", form: "Microondas", ab: "MICROWAVE", spd: 2.9, jump: 9, cd: 1.0,
    tip: "X: calienta todo a tu alrededor",
    voice: ["Hemos reducido el coste de Cloud."] },
  { id: "maca", emoji: "🏐", name: "MACA", form: "Pelota de voleibol", ab: "SPIKE", spd: 4.6, jump: 10, cd: 0.4,
    tip: "X: modo pelota — botas sin parar y arrollas",
    voice: ["¡Ja, ja, ja! ¡Qué guay!"] },
  { id: "manu", emoji: "💪", name: "MANU", form: "Forzudo con zapatos", ab: "SUPER STEP", spd: 3.2, jump: 9, cd: 0.8,
    tip: "X: salto gigantesco con impacto al caer",
    voice: ["¡Sí, señor! Déjamelo a mí, que lo vendo."] },
  { id: "pablo", emoji: "🍊", name: "PABLO", form: "Naranja", ab: "ORANGE ROLL", spd: 4.2, jump: 9.5, cd: 0.9,
    tip: "X: rueda a toda velocidad arrollando",
    voice: ["Nano, nano, nano... ¿Qué pasa, que sos de Valencia? Nano, nano."] },
  { id: "paloma", emoji: "🕊️", name: "PALOMA", form: "Paloma", ab: "FLY AWAY", spd: 4.6, jump: 9.5, cd: 0.3,
    tip: "Mantén salto para volar (barra de vuelo)",
    voice: ["Necesito cargar mi batería social."] },
  { id: "silvia", emoji: "👟", name: "SILVIA", form: "Zapatilla", ab: "SPEEDRUN", spd: 5.4, jump: 10, cd: 0.6,
    tip: "X: dash invulnerable que arrolla",
    voice: ["Este cliente no ha pagado."] },
  { id: "yair", emoji: "🪘", name: "YAIR", form: "Cajón flamenco", ab: "BULERÍA", spd: 3.8, jump: 10, cd: 0.9,
    tip: "X: se arranca por bulerías y aturde a todos los de alrededor",
    voice: ["Soy campeón de ping-pong."] }
];

export const FLY_META = {
  fw: 96,
  fh: 112,
  anims: {
    idle: { row: 0, frames: 3 },
    walk: { row: 1, frames: 4 },
    run: { row: 2, frames: 3 },
    jump: { row: 3, frames: 3 },
    attack: { row: 4, frames: 3 },
    damage: { row: 5, frames: 2 },
    death: { row: 6, frames: 5 },
    victory: { row: 7, frames: 3 }
  }
};

// Habilidad especial de cada héroe, contada para los menús (icono + qué hace)
export const POWER_INFO = {
  alejandro: { icon: "🥊", desc: "Puñetazo de mosca y, si mantienes el salto, planea por el aire." },
  ale: { icon: "🫒", desc: "Se derrama y se desliza por el suelo arrollando todo lo que pilla." },
  alvaroM: { icon: "🧮", desc: "Lanza una operación ERROR 404 que rebota y explota." },
  alvaroP: { icon: "🎙️", desc: "Onda sonora de podcast que atraviesa a varios enemigos." },
  ana: { icon: "🧗", desc: "Trepa por cualquier pared y lanza zarpazos de leona." },
  beltran: { icon: "💬", desc: "Lanza una ráfaga de mensajes de Slack que atraviesan a los enemigos y, manteniendo abajo, un escudo que lo para todo." },
  bruno: { icon: "🗿", desc: "Tira una cara al azar: cura, furia, velocidad o modo zen invencible." },
  gonzalo: { icon: "🥦", desc: "Se multiplica en tres mini-brócolis saltarines que arrasan." },
  javi: { icon: "☭", desc: "Invoca trabajadores que marchan en huelga contra los enemigos." },
  jesus: { icon: "🍺", desc: "Smash de Cruzcampo en el suelo; en el aire, se lanza en picado." },
  joseluis: { icon: "🖨️", desc: "Imprime plataformas en 3D donde las necesites (hasta 3 a la vez)." },
  josu: { icon: "🥮", desc: "Bote diagonal de panetón y rebotes de pared más potentes." },
  juan: { icon: "📻", desc: "Calienta todo a su alrededor con una onda de microondas." },
  maca: { icon: "🏐", desc: "Modo pelota: bota sin parar, corre más y arrolla." },
  manu: { icon: "💪", desc: "Super step: salto gigantesco con un impacto enorme al caer." },
  pablo: { icon: "🍊", desc: "Rueda a toda velocidad como una naranja rompiendo ladrillos." },
  paloma: { icon: "🕊️", desc: "Mantén el salto para volar con su barra de vuelo." },
  silvia: { icon: "👟", desc: "Speedrun: dash invulnerable que arrolla todo." },
  yair: { icon: "🪘", desc: "Cajón flamenco: se arranca por bulerías y el golpe de cajón y pañuelo aturde a todos los de alrededor." }
};
